# This is a basic workflow to help you get started with Actions
name: build

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  OWNER: ${{ github.actor }}
  IMAGE_NAME: ${{github.event.repository.name}}

on:
  push:
    branches:
      - "**"
      - "!development"
      - "!main"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: MVN isntall
        run: mvn install

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run unit test
        run: mvn test

